# Generated by Django 6.0.7 on 2026-10-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('petrol', 'Benzyna'), ('diesel', 'Diesel'), ('lpg', 'LPG'), ('hybrid', 'Hybryda'), ('electric', 'Elektryczny')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('passenger', 'Samochód osobowy'), ('van', 'Bus / samochód dostawczy'), ('truck', 'Samochód ciężarowy'), ('special', 'Pojazd specjalny'), ('other', 'Inny')], default='passenger', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
